# BAC — Trading Team Recommendation

**Ticker:** BAC (Bank of America)  
**Date:** March 5, 2026  
**Current Price:** $49.43

---

## Call: TRADE
## Conviction: MEDIUM

---

## Levels

| | Price | % from Current |
|--|-------|----------------|
| **Entry** | $47.00 - $49.50 | Scale in on weakness |
| **Stop** | $44.50 | -10% max risk |
| **Target** | $55.00 | +11-17% reward |

**Risk/Reward:** 1.5:1 at current / 2.2:1 at $47 entry

---

## Summary

Bank of America is a quality large-cap trading at 10x forward earnings with 14%+ EPS growth (PEG 0.71). The 9% monthly pullback on sector-wide AI fears has pushed RSI near oversold territory. While the Buffett/Berkshire selling creates headline risk, the valuation provides margin of safety. Better entry at $47 support, but current price is defensible for a scale-in approach with Q1 earnings catalyst in 6 weeks.

---

## Team Alignment

| Agent | Call | Conviction | Key Point |
|-------|------|------------|-----------|
| **Scout** | ✓ TRADE | Medium | PEG 0.71, oversold on sentiment, quality name |
| **Ant** | ✓ TRADE | Medium | Pullback in uptrend, wait for $47 or $51 reclaim preferred |
| **Jeb** | ✓ TRADE | Medium | Fair price for good business, 5.4% shareholder yield |

**Consensus:** 3/3 TRADE — Agreement on direction, slight disagreement on optimal entry timing.

---

## Execution Notes

1. **Preferred Entry:** Scale in — 50% now ($49.50), 50% at $47 if it gets there
2. **Stop Discipline:** Hard stop at $44.50 (no exceptions)
3. **Target Strategy:** Trim 50% at $53.50 (50 MA), let rest run to $55-57
4. **Position Size:** 2-3% of portfolio (medium conviction = medium size)
5. **Time Horizon:** 2-4 months (earnings catalyst Apr 14)

---

## What Would Change Our Mind

**Upgrade to HIGH conviction if:**
- Price reaches $47 support with RSI < 30
- Berkshire announces completion of BAC selling
- Positive NII guidance on Q1 call

**Downgrade to NO TRADE if:**
- Price breaks below $44 with volume
- Credit quality deterioration in Q1
- Broader bank sector enters sustained downtrend

---

*The team agrees: BAC is a buy, but patience improves the setup.*
